{% load static %}/* HEALTHAPP service worker — generated by Django template */
const VERSION = 'v1.0.0';
const STATIC_CACHE = `healthapp-static-${VERSION}`;
const RUNTIME_CACHE = `healthapp-runtime-${VERSION}`;
const OFFLINE_URL = '/offline/';

const PRECACHE_URLS = [
  OFFLINE_URL,
  '{% static "css/main.css" %}',
  '{% static "js/main.js" %}',
  '{% static "img/pwa/icon.svg" %}',
  '{% static "img/pwa/icon-maskable.svg" %}',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
      .catch((err) => console.warn('[SW] precache failed', err))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(
      keys
        .filter((k) => k !== STATIC_CACHE && k !== RUNTIME_CACHE)
        .map((k) => caches.delete(k))
    )).then(() => self.clients.claim())
  );
});

function isStaticAsset(url) {
  return url.pathname.startsWith('/static/') || url.pathname.startsWith('/media/');
}

function isApiRequest(url) {
  return url.pathname.startsWith('/api/');
}

function isHtmlRequest(request) {
  return request.mode === 'navigate' ||
    (request.method === 'GET' && request.headers.get('accept') &&
     request.headers.get('accept').includes('text/html'));
}

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only handle GET; pass everything else through (POST/PUT/DELETE = network).
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Don't intercept Django admin or websockets.
  if (url.pathname.startsWith('/admin/') || url.pathname.startsWith('/ws/')) return;

  // Cache-first for hashed static + media assets.
  if (isStaticAsset(url)) {
    event.respondWith(
      caches.match(request).then((cached) => cached || fetch(request).then((res) => {
        const copy = res.clone();
        caches.open(STATIC_CACHE).then((c) => c.put(request, copy)).catch(() => {});
        return res;
      }).catch(() => cached))
    );
    return;
  }

  // Network-first, fall back to cache, fall back to offline page for HTML.
  if (isHtmlRequest(request)) {
    event.respondWith(
      fetch(request).then((res) => {
        const copy = res.clone();
        caches.open(RUNTIME_CACHE).then((c) => c.put(request, copy)).catch(() => {});
        return res;
      }).catch(() => caches.match(request).then((cached) => cached || caches.match(OFFLINE_URL)))
    );
    return;
  }

  // Network-first for API; never cache (auth + freshness).
  if (isApiRequest(url)) return;

  // Default: stale-while-revalidate.
  event.respondWith(
    caches.match(request).then((cached) => {
      const fetchPromise = fetch(request).then((res) => {
        const copy = res.clone();
        caches.open(RUNTIME_CACHE).then((c) => c.put(request, copy)).catch(() => {});
        return res;
      }).catch(() => cached);
      return cached || fetchPromise;
    })
  );
});

// Push notification support — wired but optional.
self.addEventListener('push', (event) => {
  let data = { title: 'HEALTHAPP', body: 'You have a new notification.' };
  try { if (event.data) data = event.data.json(); } catch (_) {}
  event.waitUntil(
    self.registration.showNotification(data.title || 'HEALTHAPP', {
      body: data.body || '',
      icon: '{% static "img/pwa/icon-192.png" %}',
      badge: '{% static "img/pwa/icon-192.png" %}',
      data: { url: data.url || '/dashboard/' },
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || '/dashboard/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((wins) => {
      for (const w of wins) {
        if (w.url.includes(target) && 'focus' in w) return w.focus();
      }
      return self.clients.openWindow(target);
    })
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
